import type { Artist, Release } from "@/types/content";

export const STATIC_ARTISTS: Artist[] = [
  {
    id: 103,
    slug: "guri",
    name: "G.U.R.I",
    genre: "Progressive-House, Melodic-Techno",
    imageUrl: "/images/artists/guri/guri.png",
    bio: "G.U.R.I delivers deep hypnotic grooves anchored by ethereal pads and dark atmospheres.",
    socialLinks: {
      instagram: "https://gate.sc/?url=https%3A%2F%2Fwww.instagram.com%2Fgur_music%2F&token=a0bb9c-1-1761971723711",
      soundcloud: "https://soundcloud.com/guri",
    },
  },
  {
    id: 101,
    slug: "rafa-kao",
    name: "Rafa Kao",
    genre: "Melodic Techno",
    imageUrl: "/images/artists/rafa-kao/rafa-kao.png",
    bio: "Rafa Kao crafts cinematic melodic techno that balances dancefloor power with emotive storytelling and intricate soundscapes.",
    socialLinks: {
      instagram: "https://instagram.com/rafakao",
      soundcloud: "https://soundcloud.com/rafakao",
    },
  },
  {
    id: 102,
    slug: "gabriel-samy",
    name: "Gabriel Samy",
    genre: "Melodic Techno",
    imageUrl: "/images/artists/gabriel-samy/gabriel-samy.png",
    bio: "A fixture of the Brazilian underground scene, Gabriel Samy integrates organic instrumentation with modern club sonics.",
    socialLinks: {
      instagram: "https://instagram.com/gabrielsamy",
      spotify: "https://open.spotify.com/artist/0Jjg998wVzQv",
    },
  },
];

export const STATIC_RELEASES: Release[] = [
  {
    id: 19,
    slug: "stormdrifter",
    bundleId: "10341902",
    title: "Stormdrifter",
    artist: "Rafa Kao",
    artistSlug: "rafa-kao",
    label: "Tinnie House Records",
    bundleType: "Maxi Single",
    musicStyle: "Melodic House & Techno",
    digitalReleaseDate: "2025-06-30",
    internalReference: "TH019",
    trackCount: 3,
    coverImageUrl: "/images/artwork/stormdrifter.webp",
    imgUrl: "/images/artwork/stormdrifter.webp",
    beatportSaleUrl: "https://www.beatport.com/release/stormdrifter/5123504",
    purchaseLink: "https://www.beatport.com/release/stormdrifter/5123504",
    shareLink: "https://www.beatport.com/release/stormdrifter/5123504",
    audioFilePath: "rafa-kao/stormdrifter.mp3",
    featured: true,
    isLatest: true,
    upcoming: false,
    description: "Rafa Kao blends atmospheric synth layers with rolling percussion for an uplifting melodic techno journey that sets the tone for the label's future output.",
  },
  {
    id: 18,
    slug: "ritual",
    bundleId: "10341891",
    title: "Ritual",
    artist: "Rafa Kao & Gabriel Samy",
    artistSlug: "rafa-kao-gabriel-samy",
    label: "Tinnie House Records",
    bundleType: "Single",
    musicStyle: "Progressive House",
    digitalReleaseDate: "2024-11-15",
    internalReference: "TH018",
    trackCount: 1,
    coverImageUrl: "/images/artwork/ritual.webp",
    imgUrl: "/images/artwork/ritual.webp",
    beatportSaleUrl: "https://www.beatport.com/release/ritual/4977154",
    purchaseLink: "https://www.beatport.com/release/ritual/4977154",
    shareLink: "https://www.beatport.com/release/ritual/4977154",
    audioFilePath: "rafa-kao-gabriel-samy/ritual.mp3",
    featured: true,
    upcoming: false,
    description: "Hypnotic arps and evolving pads collide with a driving bassline in this collaboration between Rafa Kao and Gabriel Samy.",
  },
  {
    id: 17,
    slug: "aurora-ep",
    bundleId: "10341875",
    title: "Aurora EP",
    artist: "G.U.R.I",
    artistSlug: "guri",
    label: "Tinnie House Records",
    bundleType: "EP",
    musicStyle: "Deep Tech",
    digitalReleaseDate: "2024-08-09",
    internalReference: "TH017",
    trackCount: 3,
    coverImageUrl: "/images/artwork/aurora.webp",
    imgUrl: "/images/artwork/aurora.webp",
    beatportSaleUrl: "https://www.beatport.com/release/aurora/3899067",
    purchaseLink: "https://www.beatport.com/release/aurora/3899067",
    shareLink: "https://www.beatport.com/release/aurora/3899067",
    audioFilePath: "guri/aurora.mp3",
    featured: false,
    upcoming: false,
    description: "The Aurora EP explores cinematic textures across three deep-tech cuts designed for late-night floors and sunrise sets alike.",
  },
  {
    id: 16,
    slug: "magnetosphere",
    bundleId: "10341852",
    title: "Magnetosphere",
    artist: "G.U.R.I",
    artistSlug: "guri",
    label: "Tinnie House Records",
    bundleType: "Single",
    musicStyle: "Techno",
    digitalReleaseDate: "2024-05-06",
    internalReference: "TH016",
    trackCount: 1,
    coverImageUrl: "/images/artwork/magnetosphere.webp",
    imgUrl: "/images/artwork/magnetosphere.webp",
    beatportSaleUrl: "https://www.beatport.com/release/magnetosphere/3901406",
    purchaseLink: "https://www.beatport.com/release/magnetosphere/3901406",
    shareLink: "https://www.beatport.com/release/magnetosphere/3901406",
    audioFilePath: "guri/magnetosphere.mp3",
    featured: false,
    upcoming: false,
    description: "Peak-time techno with shimmering textures that nod to the label's melodic roots.",
  },
  {
    id: 15,
    slug: "morphing",
    bundleId: "10341825",
    title: "Morphing",
    artist: "G.U.R.I",
    artistSlug: "guri",
    label: "Tinnie House Records",
    bundleType: "Single",
    musicStyle: "Deep Tech",
    digitalReleaseDate: "2024-01-15",
    internalReference: "TH015",
    trackCount: 1,
    coverImageUrl: "/images/artwork/morphing.webp",
    imgUrl: "/images/artwork/morphing.webp",
    beatportSaleUrl: "https://www.beatport.com/release/morphing/4163783",
    purchaseLink: "https://www.beatport.com/release/morphing/4163783",
    shareLink: "https://www.beatport.com/release/morphing/4163783",
    audioFilePath: "guri/morphing.mp3",
    featured: false,
    upcoming: false,
    description: "An evolving soundscape that transforms seamlessly through different rhythmic and melodic territories.",
  },
];
